const courses = [
  {
    id: 'c1',
    title: 'Introduction to Machine Learning',
    description: 'Learn supervised and unsupervised ML with hands-on projects.',
    instructor: 'Dr. Ayesha Noor',
    category: 'AI / ML',
  },
  {
    id: 'c2',
    title: 'Full-Stack Web Development',
    description: 'Master the MERN stack and build scalable web apps.',
    instructor: 'Engr. Salman Qureshi',
    category: 'Web Development',
  },
  {
    id: 'c3',
    title: 'UI/UX Design Fundamentals',
    description: 'Design user-centered interfaces with real-world examples.',
    instructor: 'Sarah Ali',
    category: 'Design',
  },
  {
    id: 'c4',
    title: 'Data Structures & Algorithms',
    description: 'Optimize code and solve complex problems efficiently.',
    instructor: 'Sir Imran Ahmed',
    category: 'Computer Science',
  },
  {
    id: 'c5',
    title: 'Cloud Computing with AWS',
    description: 'Deploy and manage applications in the cloud with AWS.',
    instructor: 'Tariq Mehmood',
    category: 'Cloud',
  },
  {
    id: 'c6',
    title: 'DevOps Essentials',
    description: 'CI/CD pipelines, containerization, and automation.',
    instructor: 'Adeel Khan',
    category: 'DevOps',
  },
  {
    id: 'c7',
    title: 'Python for Beginners',
    description: 'Learn Python from scratch and automate everyday tasks.',
    instructor: 'Dr. Rabia Shaikh',
    category: 'Programming',
  },
  {
    id: 'c8',
    title: 'Cybersecurity Basics',
    description: 'Understand network threats, vulnerabilities, and mitigation.',
    instructor: 'Zeeshan Ahmad',
    category: 'Security',
  },
  {
    id: 'c9',
    title: 'React.js Advanced',
    description: 'Hooks, Context API, performance, and enterprise patterns.',
    instructor: 'Hassan Raza',
    category: 'Web Development',
  },
  {
    id: 'c10',
    title: 'SQL & Databases',
    description: 'Query design, normalization, indexing, and joins.',
    instructor: 'Maria Tanveer',
    category: 'Databases',
  },
  {
    id: 'c11',
    title: 'Natural Language Processing',
    description: 'Text analysis, embeddings, and transformers using Python.',
    instructor: 'Dr. Sameer Farooq',
    category: 'AI / ML',
  },
  {
    id: 'c12',
    title: 'Digital Marketing Strategies',
    description: 'SEO, content marketing, and conversion optimization.',
    instructor: 'Aimen Khalid',
    category: 'Business',
  },
];

export default courses;
