const courses = [
  {
    id: 'c1',
    title: 'Introduction to Machine Learning',
    description: 'Learn supervised and unsupervised ML with hands-on projects.',
    instructor: 'Dr. Ayesha Noor',
    category: 'AI / ML',
    status: 'Active',
    progress: 45,
    rating: 3.8,
    students: 6257,
    color: 'bg-gradient-to-r from-purple-500 to-blue-500',
  },
  {
    id: 'c2',
    title: 'Full-Stack Web Development',
    description: 'Master the MERN stack and build scalable web apps.',
    instructor: 'Engr. Salman Qureshi',
    category: 'Web Development',
    status: 'Completed',
    progress: 100,
    rating: 4.2,
    students: 10563,
    color: 'bg-gradient-to-r from-green-400 to-teal-500',
  },
  {
    id: 'c3',
    title: 'UI/UX Design Fundamentals',
    description: 'Design user-centered interfaces with real-world examples.',
    instructor: 'Sarah Ali',
    category: 'Design',
    status: 'Dropped',
    progress: 20,
    rating: 3.5,
    students: 7142,
    color: 'bg-gradient-to-r from-orange-400 to-yellow-500',
  },
  {
    id: 'c4',
    title: 'Data Structures & Algorithms',
    description: 'Optimize code and solve complex problems efficiently.',
    instructor: 'Sir Imran Ahmed',
    category: 'Computer Science',
    status: 'Completed',
    progress: 100,
    rating: 4.5,
    students: 8921,
    color: 'bg-gradient-to-r from-pink-500 to-red-500',
  },
  {
    id: 'c5',
    title: 'Cloud Computing with AWS',
    description: 'Deploy and manage applications in the cloud with AWS.',
    instructor: 'Tariq Mehmood',
    category: 'Cloud',
    status: 'Active',
    progress: 85,
    rating: 4.1,
    students: 10563,
    color: 'bg-gradient-to-r from-indigo-500 to-blue-500',
  },
  {
    id: 'c6',
    title: 'DevOps Essentials',
    description: 'CI/CD pipelines, containerization, and automation.',
    instructor: 'Adeel Khan',
    category: 'DevOps',
    status: 'Completed',
    progress: 100,
    rating: 3.9,
    students: 30314,
    color: 'bg-gradient-to-r from-gray-700 to-gray-900',
  },
  {
    id: 'c7',
    title: 'Python for Beginners',
    description: 'Learn Python from scratch and automate everyday tasks.',
    instructor: 'Dr. Rabia Shaikh',
    category: 'Programming',
    status: 'Dropped',
    progress: 35,
    rating: 3.6,
    students: 8764,
    color: 'bg-gradient-to-r from-pink-400 to-rose-500',
  },
  {
    id: 'c8',
    title: 'Cybersecurity Basics',
    description: 'Understand network threats, vulnerabilities, and mitigation.',
    instructor: 'Zeeshan Ahmad',
    category: 'Security',
    status: 'Active',
    progress: 60,
    rating: 4.3,
    students: 7321,
    color: 'bg-gradient-to-r from-emerald-500 to-green-500',
  },
  {
    id: 'c9',
    title: 'React.js Advanced',
    description: 'Hooks, Context API, performance, and enterprise patterns.',
    instructor: 'Hassan Raza',
    category: 'Web Development',
    status: 'Completed',
    progress: 100,
    rating: 4.6,
    students: 11824,
    color: 'bg-gradient-to-r from-blue-500 to-indigo-600',
  },
  {
    id: 'c10',
    title: 'SQL & Databases',
    description: 'Query design, normalization, indexing, and joins.',
    instructor: 'Maria Tanveer',
    category: 'Databases',
    status: 'Active',
    progress: 75,
    rating: 4.0,
    students: 5423,
    color: 'bg-gradient-to-r from-yellow-400 to-orange-500',
  },
  {
    id: 'c11',
    title: 'Natural Language Processing',
    description: 'Text analysis, embeddings, and transformers using Python.',
    instructor: 'Dr. Sameer Farooq',
    category: 'AI / ML',
    status: 'Completed',
    progress: 100,
    rating: 4.8,
    students: 9621,
    color: 'bg-gradient-to-r from-fuchsia-500 to-pink-500',
  },
  {
    id: 'c12',
    title: 'Digital Marketing Strategies',
    description: 'SEO, content marketing, and conversion optimization.',
    instructor: 'Aimen Khalid',
    category: 'Business',
    status: 'Active',
    progress: 55,
    rating: 4.1,
    students: 4375,
    color: 'bg-gradient-to-r from-cyan-500 to-sky-500',
  },
];

export default courses;
